version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.99.101:31112
functions:
  valve-product-photos-4-success:
    lang: node10-express
    handler: ./product-photos-4-success
    image: prabkumar/valve-product-photos-4-success:latest
    read_timeout: 500 # seconds
    write_timeout: 500 # seconds
    exec_timeout: 0s # disable
    write_debug: true
    