version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.99.101:31112
functions:
  trapeze-product-purchase-authorize-cc:
    lang: node10-express
    handler: ./product-purchase-authorize-cc
    image: prabkumar/trapeze-product-purchase-3-authorize-cc:latest
    read_timeout: 500 # seconds
    write_timeout: 500 # seconds
    exec_timeout: 0s # disable
    write_debug: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_CREDIT_CARDS_NAME: 'creditCardsName'
      HOST: 'mysql.default.svc.cluster.local'
      USER: 'abc'
      PASS: 'xyz'
